/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'artur' at '05.04.17 10:24' with Gradle 3.0
 *
 * @author artur, @date 05.04.17 10:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
